# Generated by Django 4.2.3 on 2023-10-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="tipe",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "management"),
                    (2, "resepsionis"),
                    (3, "Room Services"),
                    (4, "Chef"),
                    (5, "Security"),
                ],
                default=2,
                null=True,
            ),
        ),
    ]
