# Generated by Django 4.2.3 on 2023-10-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kamar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipe_kamar",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "regular"),
                            (2, "suite"),
                            (3, "deluxe"),
                            (4, "VIP"),
                            (5, "Family"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "tipe_kasur",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Twin bed"),
                            (2, "Double bed"),
                            (3, "Queen bed"),
                            (4, "King bed"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                ("harga_kamar", models.DecimalField(decimal_places=2, max_digits=65)),
            ],
            options={
                "verbose_name": "kamar",
                "verbose_name_plural": "kamar",
            },
        ),
        migrations.CreateModel(
            name="NomorKamar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_kamar", models.IntegerField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "tipe_kamar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.kamar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nomorkamar",
                "verbose_name_plural": "Nomorkamar",
            },
        ),
    ]
