# Generated by Django 4.2.3 on 2023-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kamar",
            name="kapasitas",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
