# Generated by Django 4.2.3 on 2023-10-24 21:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("room", "0002_kamar_kapasitas"),
        ("reservation", "0002_invoice_roomtypeinvoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CICO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("date_check_in", models.DateTimeField(blank=True, null=True)),
                ("date_check_out", models.DateTimeField(blank=True, null=True)),
                ("status_ci", models.BooleanField(default=False)),
                ("status_co", models.BooleanField(default=False)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.invoice",
                    ),
                ),
                (
                    "no_kamar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.nomorkamar",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
