# Generated by Django 4.2.3 on 2023-10-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_menu_pesan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pesan",
            name="jumlah_pesanan",
        ),
        migrations.RemoveField(
            model_name="pesan",
            name="pesanan",
        ),
        migrations.RemoveField(
            model_name="pesan",
            name="total",
        ),
        migrations.AddField(
            model_name="pesan",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Waiting List"), (2, "Cooking"), (3, "Delivered")],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="CatatanPesanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_pesanan", models.IntegerField()),
                ("total_harga", models.DecimalField(decimal_places=2, max_digits=65)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.pesan"
                    ),
                ),
                (
                    "pesanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.menu"
                    ),
                ),
            ],
        ),
    ]
